BiocManager::install("GenomicAlignments")
update all
install.packages("protti")
install.packages("UniprotR")
library(UniprotR)
library(protti)
acc_num <- c("P08839", "Q8XBL3","A7ZPL7","A0A7I6H8A9","Q3YZC6") 
GeoTerms <- GetProteinGOInfo(acc_num)
PlotGoInfo(GeoTerms)
PlotGOAll(GeoTerms)
GetPathology_Biotech(acc_num)
fetch_uniprot(acc_num)
fetch_pdb("1zmr")
fetch_alphafold_prediction(acc_num)
